# Generated by Django 6.0.4 on 2026-04-10 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_enable_pgvector'),
    ]

    operations = [
    ]
